// apps/angular-portfolio/src/app/events-calendar/events-calendar.component.ts
import { Component, OnInit } from '@angular/core';
import { RevniqueCalendarComponent } from '../revnique-calendar/revnique-calendar.component';
import { CommonModule } from '@angular/common';
import { FormControl, FormGroup, FormsModule, ReactiveFormsModule } from '@angular/forms';
import { faCaretUp, faCaretDown, faTrash } from '@fortawesome/free-solid-svg-icons';
import { FontAwesomeModule } from '@fortawesome/angular-fontawesome';
import { Store } from '@ngrx/store';
import { CalendarEvent, PortfolioState } from '../../store/portfolio-store/portfolio.state';
import { PortfolioActions, selectPortfolioState } from '../../store/portfolio-store/portfolio.actions';

@Component({
  selector: 'app-events-calendar',
  imports: [RevniqueCalendarComponent, CommonModule, FormsModule, ReactiveFormsModule, FontAwesomeModule],
  templateUrl: './events-calendar.component.html',
  styleUrl: './events-calendar.component.scss'
})
export class EventsCalendarComponent implements OnInit{
  constructor(private store: Store<{ portfolio: PortfolioState }>) {}

  portfolioState$ = this.store.select(selectPortfolioState);
  showSummary = false;
  faCaretUp = faCaretUp;
  faCaretDown = faCaretDown;
  faTrash = faTrash;
  eventForm = new FormGroup({
    title: new FormControl(''),
    eventDate: new FormControl(''),
    eventColor: new FormControl('red')
  });
  eventColor = ['red', 'orange', 'yellow'];

  ngOnInit(){
    this.store.dispatch(PortfolioActions.loadCalendarEvents());
  }

  save(){
    if (this.eventForm.invalid) {
      return;
    }
    this.store.dispatch(PortfolioActions.addCalendarEvent({
      event: {
        id: '',
        title: this.eventForm.get('title')?.value!,
        eventDate: this.eventForm.get('eventDate')?.value!,
        eventColor: this.eventForm.get('eventColor')?.value!
      }
    }));
    this.resetEventForm();
  }

  deleteEvent(selectedEvent: CalendarEvent){
    console.log("deleteEvent", selectedEvent.id);
    this.store.dispatch(PortfolioActions.deleteCalendarEvent({
      id: selectedEvent.id
    }));
  }
  
  resetEventForm(){
    this.eventForm.reset();
  }

  toggleSummary(){
    this.showSummary = !this.showSummary;
  }
}

<div class="main-content-header">
    <div class="summary">
        <h1>Events Calendar</h1>
        <div class="summary-subheader">(add events to calendar) <span class="summary-subheader-link" (click)="toggleSummary()"><fa-icon *ngIf="showSummary" [icon]="faCaretUp"></fa-icon><fa-icon *ngIf="!showSummary" [icon]="faCaretDown"></fa-icon></span></div>
        <div class="summary-text" [ngClass]="{'show': showSummary,'hide': !showSummary}">
            This page allows you to add events to the calendar. You can add events by clicking the "Save" button.
        </div>
    </div>
</div>
<div class="main-content-body">
    <div class="calendar-content-container" *ngIf="portfolioState$ | async as portfolioState">
        <div class="main-calendar-container">
            <!-- <pre>{{portfolioState | json}}</pre> -->
            <h1>Calendar</h1>
            <div *ngIf="portfolioState.isPending">
                <div class="skeleton-loader-container">
                    <div class="skeleton-loader-base"></div>
                    <div class="skeleton-loader-indicator"></div>
                </div>
            </div>
            <app-revnique-calendar *ngIf="!portfolioState.isPending" [redDays]="portfolioState.redDays" [orangeDays]="portfolioState.orangeDays" [yellowDays]="portfolioState.yellowDays"></app-revnique-calendar>
            <div class="selected-event-container" *ngIf="(portfolioState.selectedCalendarEvent && portfolioState.selectedCalendarEvent.id)">
                <div class="selected-event-container-content">
                    <div class="event-color-square" [ngClass]="{'red-day': portfolioState.selectedCalendarEvent.eventColor === 'red', 
                            'orange-day': portfolioState.selectedCalendarEvent.eventColor === 'orange', 
                            'yellow-day': portfolioState.selectedCalendarEvent.eventColor === 'yellow'}">&nbsp;&nbsp;&nbsp;
                    </div>
                    <div>
                        <span class="event-color-text">{{portfolioState.selectedCalendarEvent.title}}</span>
                    </div>
                </div>
                <div>
                    <fa-icon [icon]="faTrash" class="delete-icon" (click)="deleteEvent(portfolioState.selectedCalendarEvent)"></fa-icon>
                </div>
            </div>
        </div>
        <div class="event-form-container">
            <h1>Add Event</h1>
            <form class="form-container" [formGroup]="eventForm">
                <div class="form-group">
                    <label htmlFor="title">Event Name</label>
                    <input type="text" class="form-field" formControlName="title" maxlength="50" />
                </div>
                <div class="form-group">
                    <label htmlFor="eventDate">Date</label>
                    <input type="date" class="form-field" formControlName="eventDate" />
                </div>
                <div class="event-color-radiocontainer">
                    <div class="event-color-container">
                        <input type="radio" formControlName="eventColor" id="red" value="red" />
                        <label for="red">
                            <span class="event-color-text">Red</span><span class="event-color-square red-day">&nbsp;&nbsp;&nbsp;</span>
                        </label>
                    </div>
                    <div class="event-color-container">
                        <input type="radio" formControlName="eventColor" id="orange" value="orange" />
                        <label for="orange">
                            <span class="event-color-text">Orange</span><span class="event-color-square orange-day">&nbsp;&nbsp;&nbsp;</span>
                        </label> 
                    </div>
                    <div class="event-color-container">
                        <input type="radio" formControlName="eventColor" id="yellow" value="yellow" />
                        <label for="yellow">
                            <span class="event-color-text">Yellow</span><span class="event-color-square yellow-day">&nbsp;&nbsp;&nbsp;</span>
                        </label> 
                    </div>
                </div>
                <div class="button-container">
                    <button type="button" (click)="save()">Save</button>
                    <span class="error-message" [ngClass]="{'show': eventForm.invalid, 'hide': eventForm.valid}">Please fill out all fields</span>
                </div>
            </form>
        </div>
    </div>
</div>

// apps/react-portfolio/src/EventsCalendar/EventsCalendar.tsx
import './EventsCalendar.scss';
import { useSelector, useDispatch } from 'react-redux';
import { CalendarEvent, PortfolioState } from '../store/PortfolioStore/portfolio.state';
import { faCaretUp, faCaretDown, faTrash } from '@fortawesome/free-solid-svg-icons';
import { FontAwesomeIcon } from '@fortawesome/react-fontawesome';
import { useState, useEffect } from 'react';
import RevniqueCalendar from '../RevniqueCalendar/RevniqueCalendar';
import { addCalendarEvent, loadCalendarEvents } from '../store/PortfolioStore/portfolio.actions';
export const EventsCalendar = () => {
    const state = useSelector((state:any) => state.portfolioReducer as PortfolioState);
    const [showSummary, setShowSummary] = useState(false);
    const dispatch = useDispatch();
    const toggleSummary = () => {
        setShowSummary(!showSummary);
    }
    const deleteEvent = (event: CalendarEvent) => {
        console.log('deleteEvent', event);
    }
    const saveEvent = () => {
        if (eventTitle === '' || eventDate === '' || eventColor === '') {
            return;
        }
        const event: CalendarEvent = {
            title: eventTitle,
            eventDate: eventDate,
            eventColor: eventColor
        }
        dispatch(addCalendarEvent(event));
    }
    const [eventTitle, setEventTitle] = useState('');
    const [eventDate, setEventDate] = useState('');
    const [eventColor, setEventColor] = useState('');
    useEffect(() => {
        dispatch(loadCalendarEvents());
    }, []);
    return (
        <>
            <div className="main-content-header">
                <div className="summary">
                    <h1>Events Calendar</h1>
                    <div className="summary-subheader">(add events to calendar) <span className="summary-subheader-link" onClick={toggleSummary}><FontAwesomeIcon icon={showSummary ? faCaretUp : faCaretDown} /></span></div>
                    <div className={`summary-text ${showSummary ? 'show' : 'hide'}`}>
                        This page allows you to add events to the calendar. You can add events by clicking the "Save" button.
                    </div>
                </div>
            </div>
            <div className="main-content-body events-calendar">
                <div className="calendar-content-container">
                    <div className="main-calendar-container">
                        <h1>Calendar</h1>
                        {state.isPending && (
                            <div className="skeleton-loader-container">
                                <div className="skeleton-loader-base"></div>
                                <div className="skeleton-loader-indicator"></div>
                            </div>
                        )}
                        {!state.isPending && (
                            <RevniqueCalendar redDays={state.redDays} orangeDays={state.orangeDays} yellowDays={state.yellowDays} />
                        )}
                        {state.selectedCalendarEvent && state.selectedCalendarEvent.id && (
                            <div className="selected-event-container">
                                <div className="selected-event-container-content">
                                    <div className={`event-color-square ${state.selectedCalendarEvent.eventColor === 'red' ? 'red-day' : state.selectedCalendarEvent.eventColor === 'orange' ? 'orange-day' : 'yellow-day'}`}>&nbsp;&nbsp;&nbsp;</div>
                                    <div>
                                        <span className="event-color-text">{state.selectedCalendarEvent.title}</span>
                                    </div>
                                </div>
                                <div>
                                    <FontAwesomeIcon icon={faTrash} className="delete-icon" onClick={() => deleteEvent(state.selectedCalendarEvent)} />
                                </div>
                            </div>
                        )}
                    </div>
                    <div className="event-form-container">
                        <h1>Add Event</h1>
                        <form className="form-container">
                            <div className="form-group">
                                <label htmlFor="title">Event Name</label>
                                <input type="text" className="form-field" name="title" maxLength={50} onChange={(e) => setEventTitle(e.target.value)} />
                            </div>
                            <div className="form-group">
                                <label htmlFor="eventDate">Date</label>
                                <input type="date" className="form-field" name="eventDate" onChange={(e) => setEventDate(e.target.value)} />
                            </div>
                            <div className="event-color-radiocontainer">
                                <div className="event-color-container">
                                    <input type="radio" name="eventColor" id="red" value="red" onChange={(e) => setEventColor(e.target.value)} />
                                    <label htmlFor="red">
                                        <span className="event-color-text">Red</span><span className="event-color-square red-day">&nbsp;&nbsp;&nbsp;</span>
                                    </label>
                                </div>
                                <div className="event-color-container">
                                    <input type="radio" name="eventColor" id="orange" value="orange" onChange={(e) => setEventColor(e.target.value)} />
                                    <label htmlFor="orange">
                                        <span className="event-color-text">Orange</span><span className="event-color-square orange-day">&nbsp;&nbsp;&nbsp;</span>
                                    </label>
                                </div>
                                <div className="event-color-container">
                                    <input type="radio" name="eventColor" id="yellow" value="yellow" onChange={(e) => setEventColor(e.target.value)} />
                                    <label htmlFor="yellow">
                                        <span className="event-color-text">Yellow</span><span className="event-color-square yellow-day">&nbsp;&nbsp;&nbsp;</span>
                                    </label>
                                </div>
                            </div>
                            <div className="button-container">
                                <button type="button" onClick={saveEvent}>Save</button>
                                <span className={`error-message ${eventTitle === '' || eventDate === '' || eventColor === '' ? 'show' : 'hide'}`}>Please fill out all fields</span>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </>
    )
}
