// angular/angular-portfolio/src/app/buck-lite/buck-lite.component.ts
import { Component } from '@angular/core';

@Component({
  selector: 'app-buck-lite',
  standalone: true,
  imports: [],
  templateUrl: './buck-lite.component.html',
  styleUrl: './buck-lite.component.scss'
})
export class BuckLiteComponent {

}

<div class="main-content-header">
    <div class="summary">
        <h1>BuckLite</h1>
        <p>BuckLite is a simple budgeting app that allows you to track your income and expenses.</p>
    </div>
</div>
<div class="main-content-body">
    <div class="content-container">
        <div>BuckLite content</div>
    </div>
</div>

// react/react-portfolio/src/BuckLite/BuckLite.tsx
export default function BuckLite() {
    return (
        <>
            <div className="main-content-header">
                <div className="summary">
                    <h1>BuckLite</h1>
                    <p>BuckLite is a simple budgeting app that allows you to track your income and expenses.</p>
                </div>
            </div>
            <div className="main-content-body">
                <div className="content-container">
                    <div>BuckLite content</div>
                </div>
            </div>
        </>
    )
}
