// react/react-portfolio/src/SideBar/SideBar.tsx
import './SideBar.scss';
import { FontAwesomeIcon } from '@fortawesome/react-fontawesome';
import { NavLink } from 'react-router';
import { library } from '@fortawesome/fontawesome-svg-core';
import { faMoneyBill, faCode, faClose, faBars } from '@fortawesome/free-solid-svg-icons';
import { useDispatch, useSelector } from 'react-redux';
import { toggleSideBar as toggleSideBarAction } from '../store/root.actions';
import { RootState } from '../store/root.state';
library.add(faMoneyBill, faCode, faClose, faBars);

export default function SideBar() {
    const dispatch = useDispatch();
    const state = useSelector((state: any) => state.reducer as RootState);
    const sideBarOpen = state.sidebarState.sidebarIsOpen;
    const toggleSideBar = () => {
        dispatch(toggleSideBarAction());
    }
    
    return (
        <div className={`side-bar ${sideBarOpen ? 'open' : 'closed'}`}>
        <div className="side-bar-header">Projects<FontAwesomeIcon className="fa-icon" icon="close" onClick={toggleSideBar} /></div>
        <ul>
            <li><NavLink to="/bucklite" className={({ isActive }) => isActive ? 'selected' : ''}><FontAwesomeIcon className="fa-icon" icon="money-bill" /> BuckLite</NavLink></li>
            <li><NavLink to="/components" className={({ isActive }) => isActive ? 'selected' : ''}><FontAwesomeIcon className="fa-icon" icon="code" /> Components</NavLink></li>
        </ul>
    </div>
    )
}

// angular/angular-portfolio/src/app/side-bar/side-bar.component.ts
import { Component, OnInit } from '@angular/core';
import { Store } from '@ngrx/store';
import { RootActions, selectRootState } from '../../store/root.actions';
import { faClose, faCode, faMoneyBill } from '@fortawesome/free-solid-svg-icons';
import { FontAwesomeModule } from '@fortawesome/angular-fontawesome';
import { CommonModule } from '@angular/common';

@Component({
  selector: 'app-side-bar',
  imports: [FontAwesomeModule, CommonModule],
  templateUrl: './side-bar.component.html',
  styleUrl: './side-bar.component.scss'
})


export class SideBarComponent implements OnInit {
  rootState$ = this.store.select(selectRootState);
  sidebarIsOpen = false;
  faClose = faClose;
  faCode = faCode;
  faMoneyBill = faMoneyBill;
  constructor(private store: Store) {}
  ngOnInit() {
    this.rootState$.subscribe((state) => {
      console.log('here', state);
      this.sidebarIsOpen = state.sidebarState.sidebarIsOpen;
    });
  }
  toggleSideBar() {
    this.store.dispatch(RootActions.toggleSideBar());
  }
}

<div class="side-bar" [ngClass]="{'open': sidebarIsOpen, 'closed': !sidebarIsOpen}">
    <div class="side-bar-header">Projects<fa-icon class="fa-icon" [icon]="faClose" (click)="toggleSideBar()" /></div>
    <ul>
        <li><a routerLink="/bucklite" routerLinkActive="selected"><fa-icon class="fa-icon" [icon]="faMoneyBill" /> BuckLite</a></li>
        <li><a routerLink="/components" routerLinkActive="selected"><fa-icon class="fa-icon" [icon]="faCode" /> Components</a></li>
    </ul>
</div>
