// apps/react-portfolio/src/ValueBar/ValueBar.tsx
import './ValueBar.scss';
export default function ValueBar({ valueBarPositiveHeight, isHorizontal, length, thickness }: { valueBarPositiveHeight: number, isHorizontal: boolean, length: number, thickness: number }) {
    const valueBarNegativeHeight = 100 - valueBarPositiveHeight;
    return (
        <>
            {isHorizontal ? (
                <div className="value-bar-container-wrapper-horizontal">
                    <div className="value-bar-container" style={{ width: `${length}px`, height: `${thickness}px` }}>
                        <div className="value-bar-positive" style={{ width: `${valueBarPositiveHeight}%` }}></div>
                        <div className="value-bar-negative" style={{ width: `${valueBarNegativeHeight}%` }}></div>
                    </div>
                    <div className="value-bar-label">
                        <span>{valueBarPositiveHeight}</span>
                    </div>
                </div>
            ) : (
                <div className="value-bar-container-wrapper">
                    <div className="value-bar-container" style={{ height: `${length}px`, width: `${thickness}px` }}>
                        <div className="value-bar-negative" style={{ height: `${valueBarNegativeHeight}%` }}></div>
                        <div className="value-bar-positive" style={{ height: `${valueBarPositiveHeight}%` }}></div>
                    </div>
                    <div className="value-bar-label">
                        <span>{valueBarPositiveHeight}</span>
                    </div>
                </div>
            )}
        </>
    )
}

// apps/angular-portfolio/src/app/value-bar/value-bar.component.ts
import { Component, Input, SimpleChanges } from '@angular/core';
import { CommonModule } from '@angular/common';
@Component({
  selector: 'app-value-bar',
  imports: [CommonModule],
  templateUrl: './value-bar.component.html',
  styleUrl: './value-bar.component.scss'
})
export class ValueBarComponent {
  @Input() isHorizontal: boolean = false;
  @Input() length: number = 100;
  @Input() thickness: number = 10;
  @Input() valueBarPositiveHeight: number = 1;
  valueBarNegativeHeight: number = 100 - this.valueBarPositiveHeight;

  ngOnChanges(changes: SimpleChanges): void {
    if (changes['valueBarPositiveHeight']) {
      this.valueBarNegativeHeight = 100 - this.valueBarPositiveHeight;
    }
  }
}

<div class="value-bar-container-wrapper-horizontal" *ngIf="isHorizontal">
    <div class="value-bar-container" [style.width.px]="length" [style.height.px]="thickness">
        <div class="value-bar-positive" [style.width.%]="valueBarPositiveHeight"></div>
        <div class="value-bar-negative" [style.width.%]="valueBarNegativeHeight"></div>
    </div>
    <div class="value-bar-label">
        <span>{{valueBarPositiveHeight}}</span>
    </div>
</div>
<div class="value-bar-container-wrapper" *ngIf="!isHorizontal">
    <div class="value-bar-container" [style.height.px]="length" [style.width.px]="thickness">
        <div class="value-bar-negative" [style.height.%]="valueBarNegativeHeight" ></div>
        <div class="value-bar-positive" [style.height.%]="valueBarPositiveHeight" ></div>
    </div>
    <div class="value-bar-label">
        <span>{{valueBarPositiveHeight}}</span>
    </div>
</div>
