// apps/angular-portfolio/src/app/default-page/default-page.component.ts
import { Component } from '@angular/core';
import { faHandPointUp, faExternalLink } from '@fortawesome/free-solid-svg-icons';
import { FontAwesomeModule } from '@fortawesome/angular-fontawesome';
@Component({
  selector: 'app-default-page',
  imports: [FontAwesomeModule],
  templateUrl: './default-page.component.html',
  styleUrl: './default-page.component.scss'
})
export class DefaultPageComponent {
  faHandPointUp = faHandPointUp;
  faExternalLink = faExternalLink;
}

<div class="default-page">
    <div class="default-page-content">
        <div class="default-page-content-container">
            <div>
                <div class="default-page-title">This website demonstrates</div>
                <ul>
                    <li>&mdash;&nbsp;Angular 19 with NgRx state management</li>
                    <li>&mdash;&nbsp;Light/Dark theming based on computer defaults</li>
                    <li>&mdash;&nbsp;GraphQL API via AWS AppSync & DynamoDB</li>
                    <li>&mdash;&nbsp;Responsive Web Design targeting iPhone SE mobile viewport</li>
                    <li>&mdash;&nbsp;pixel perfect sister site built in React 18</li>
                    <li>&mdash;&nbsp;AWS Amplify deployment of Monorepo to separate subdomains</li>
                    <li class="external-link-container"><fa-icon [icon]="faExternalLink" class="hand-icon"></fa-icon>&nbsp;<a href="https://github.com/revnique/portfolio" target="_blank" rel="noopener noreferrer">https://github.com/revnique/portfolio</a>
                        <span class="external-link-text">&nbsp;[monorepo source]</span>
                    </li>
                </ul>
            </div>
        </div>
    </div>
    <div class="hand-icon-container">
        <fa-icon [icon]="faHandPointUp" class="hand-icon" />
        <div class="hand-icon-text">React Twin Site</div>
    </div>
</div>

// apps/react-portfolio/src/DefaultPage/DefaultPage.tsx
import './DefaultPage.scss';
import { FontAwesomeIcon } from '@fortawesome/react-fontawesome';
import { faExternalLink, faHandPointUp } from '@fortawesome/free-solid-svg-icons';

export default function DefaultPage() {
    return (
        <div className="default-page">
            <div className="default-page-content">
                <div className="default-page-content-container">
                    <div>
                        <div className="default-page-title">This website demonstrates</div>
                        <ul>
                            <li>&mdash;&nbsp;React 18 with Redux state management</li>
                            <li>&mdash;&nbsp;Light/Dark theming based on computer defaults</li>
                            <li>&mdash;&nbsp;GraphQL API via AWS AppSync & DynamoDB</li>
                            <li>&mdash;&nbsp;Responsive Web Design targeting iPhone SE mobile viewport</li>
                            <li>&mdash;&nbsp;pixel perfect sister site built in Angular 19</li>
                            <li>&mdash;&nbsp;AWS Amplify deployment of Monorepo to separate subdomains</li>
                            <li className="external-link-container"><FontAwesomeIcon icon={faExternalLink} />&nbsp;
                                <a href="https://github.com/revnique/portfolio" target="_blank" rel="noopener noreferrer">https://github.com/revnique/portfolio</a>
                                <span className="external-link-text">
                                    &nbsp;[monorepo source]
                                </span>
                            </li>
                        </ul>
                    </div>
                </div>
            </div>
            <div className="hand-icon-container">
                <FontAwesomeIcon icon={faHandPointUp} className="hand-icon" />
                <div className="hand-icon-text">Angular Twin Site</div>
            </div>
        </div>
    );
}
