// apps/react-portfolio/src/Header/Header.tsx
import './Header.scss';
import { FontAwesomeIcon } from '@fortawesome/react-fontawesome';
import { faBars, faHome } from '@fortawesome/free-solid-svg-icons';
import { library } from '@fortawesome/fontawesome-svg-core';
library.add(faBars, faHome);
import { useDispatch } from 'react-redux';
import { toggleSideBar as toggleSideBarAction } from '../store/root.actions';

export default function Header() {
    const dispatch = useDispatch();
    const toggleSideBar = () => {
        dispatch(toggleSideBarAction());
    }
    const page = window.location.href.split('/')[3];
    const isLocalhost = window.location.href.indexOf('http://localhost:') === 0;
    const url = isLocalhost ? 'http://localhost:5177' : 'https://angular.revnique.works';
    const homeUrl = isLocalhost ? 'http://localhost:37777' : 'https://revnique.works';
    const gotToAngular = () => {
        if (page === 'bucklite') {
          window.location.href = `${url}/bucklite`;
        } else if (page === 'components') {
          window.location.href = `${url}/components`;
        } else {
          window.location.href = `${url}/`;
        }
    }
    const goToHome = () => {
        window.location.href = `${homeUrl}/`;
    }
    return (
        <div className="header">
            <div className="side-bar-toggle" onClick={toggleSideBar}><FontAwesomeIcon className="fa-icon" icon={faBars} /></div>
            <div className="header-left">
                <div className="home-link" onClick={goToHome}>
                    <a href={homeUrl}><FontAwesomeIcon className="fa-icon" icon={faHome} /></a>
                </div>
                <div className="header-title">
                    <h1>React Portfolio</h1>
                </div>
            </div>
            <div className="header-right">
                <div className="logo-container selected">
                    <img className="logo" src="/react-logo.png" alt="Revnique's React Portfolio" />
                </div>
                <div className="logo-container">
                    <img className="logo" src="/angular-logo.png" alt="Revnique's Angular Portfolio" onClick={gotToAngular} />
                </div>
            </div>
        </div>
    )
}

// apps/angular-portfolio/src/app/header/header.component.ts
import { Component } from '@angular/core';
import { faBars, faClose, faHome } from '@fortawesome/free-solid-svg-icons';
import { FontAwesomeModule } from '@fortawesome/angular-fontawesome';
import { CommonModule } from '@angular/common';
import { Store } from '@ngrx/store';
import { RootActions } from '../../store/root.actions';

@Component({
  selector: 'app-header',
  imports: [FontAwesomeModule, CommonModule],
  templateUrl: './header.component.html',
  styleUrl: './header.component.scss'
})
export class HeaderComponent {
  faBars = faBars;
  faClose = faClose;
  faHome = faHome;
  isLocalhost = window.location.href.indexOf('http://localhost:') === 0;
  url = this.isLocalhost ? 'http://localhost:5177' : 'https://angular.revnique.works';
  homeUrl = this.isLocalhost ? 'http://localhost:37777' : 'https://revnique.works';
  constructor(private store: Store) {}
  toggleSideBar() {
    this.store.dispatch(RootActions.toggleSideBar());
  }

  goToHome() {
    window.location.href = this.homeUrl;
  }

  gotoReact() {
    const page = window.location.href.split('/')[3];
    const url = window.location.href.includes('localhost') ? 'http://localhost:5173' : 'https://react.revnique.works';
    if (page === 'bucklite') {
      window.location.href = `${url}/bucklite`;
    } else if (page === 'components') {
      window.location.href = `${url}/components`;
    } else {
      window.location.href = `${url}/`;
    }
  }
}



<div class="header">
    <div class="side-bar-toggle" (click)="toggleSideBar()"><fa-icon class="fa-icon" [icon]="faBars" /></div>
    <div class="header-left">
        <div class="home-link" (click)="goToHome()">
            <a [href]="homeUrl"><fa-icon class="fa-icon" [icon]="faHome" /></a>
        </div>
        <div class="header-title">
            <h1>Angular Portfolio</h1>
        </div>
    </div>
    <div class="header-right">
        <div class="logo-container">
            <img class="logo" src="/react-logo.png" alt="Revnique's React Portfolio" (click)="gotoReact()" />
        </div>
        <div class="logo-container selected">
            <img class="logo" src="/angular-logo.png" alt="Revnique's Angular Portfolio"/>
        </div>
    </div>
</div>
