// react/react-portfolio/src/Header/Header.tsx
import './Header.scss';
import { FontAwesomeIcon } from '@fortawesome/react-fontawesome';
import { faBars } from '@fortawesome/free-solid-svg-icons';
import { library } from '@fortawesome/fontawesome-svg-core';
library.add(faBars);
import { useDispatch } from 'react-redux';
import { toggleSideBar as toggleSideBarAction } from '../store/root.actions';

export default function Header() {
    const dispatch = useDispatch();
    const toggleSideBar = () => {
        dispatch(toggleSideBarAction());
    }
    const gotToAngular = () => {
        const page = window.location.href.split('/')[3];
        if (page === 'bucklite') {
          window.location.href = 'http://localhost:5177/bucklite';
        } else if (page === 'components') {
          window.location.href = 'http://localhost:5177/components';
        } else {
          window.location.href = 'http://localhost:5177/';
        }
    }
    return (
        <div className="header">
            <div className="side-bar-toggle" onClick={toggleSideBar}><FontAwesomeIcon className="fa-icon" icon="bars" /></div>
            <div className="header-left">
                <h1>Revnique's React Portfolio</h1>
            </div>
            <div className="header-right">
                <div className="logo-container selected">
                    <img className="logo" src="/react-logo.png" alt="Revnique's React Portfolio" />
                </div>
                <div className="logo-container">
                    <img className="logo" src="/angular-logo.png" alt="Revnique's Angular Portfolio" onClick={gotToAngular} />
                </div>
            </div>
        </div>
    )
}

// angular/angular-portfolio/src/app/header/header.component.ts
import { Component } from '@angular/core';
import { faBars, faClose } from '@fortawesome/free-solid-svg-icons';
import { FontAwesomeModule } from '@fortawesome/angular-fontawesome';
import { CommonModule } from '@angular/common';
import { Store } from '@ngrx/store';
import { RootActions } from '../../store/root.actions';

@Component({
  selector: 'app-header',
  imports: [FontAwesomeModule, CommonModule],
  templateUrl: './header.component.html',
  styleUrl: './header.component.scss'
})
export class HeaderComponent {
  faBars = faBars;
  faClose = faClose;
  constructor(private store: Store) {}
  toggleSideBar() {
    this.store.dispatch(RootActions.toggleSideBar());
  }

  gotoReact() {
    const page = window.location.href.split('/')[3];
    if (page === 'bucklite') {
      window.location.href = 'http://localhost:5173/bucklite';
    } else if (page === 'components') {
      window.location.href = 'http://localhost:5173/components';
    }
  }
}
