// apps/react-portfolio/src/RevniqueCalendar/RevniqueCalendar.tsx
import React from 'react';
import { faChevronRight } from "@fortawesome/free-solid-svg-icons";
import { FontAwesomeIcon } from "@fortawesome/react-fontawesome";
import "./RevniqueCalendar.scss";
import { faChevronLeft } from "@fortawesome/free-solid-svg-icons";
import { Day } from "./day.interface";
import './date';
import { useEffect, useState } from "react";
import { CalendarEvent } from "../store/PortfolioStore/portfolio.state";
import { useDispatch } from 'react-redux';
import { selectCalendarEvent } from '../store/PortfolioStore/portfolio.actions';
interface RevniqueCalendarProps {
    redDays: CalendarEvent[];
    yellowDays: CalendarEvent[];
    orangeDays: CalendarEvent[];
}

const RevniqueCalendar: React.FC<RevniqueCalendarProps> = ({ redDays, yellowDays, orangeDays }) => {
    const dispatch = useDispatch();
    const calInfo = {
        showTopRow: true,
        showBottomRow: true,
        currentDate: new Date(),
        currentJSMonthNumber: 0,
        currentMonthName: '',
        currentMonthDays: -1,
        currentYear: 0,
        prevMonthDays: 0,
        currentMonthFirstDayOfWeek: -1,
        currentMonthFirstDayOfWeekName: '',
        dayList: [] as Day[],
    }
    const [calInfoState, setCalInfoState] = useState(calInfo);
    const daysInMonth = (year: number, month: number) => new Date(year, month, 0).getDate();
    const daysOfWeek = ['sunday', 'monday', 'tuesday', 'wednesday', 'thursday', 'friday', 'saturday'];


    const generateCalendar = (d: Date) => {
        calInfo.currentDate = d;
        console.log("generateCalendar", d);
        calInfo.currentJSMonthNumber = d.getMonth();
        calInfo.currentMonthName = d.getMonthName();

        calInfo.currentYear = d.getFullYear();
        calInfo.currentMonthDays = daysInMonth(calInfo.currentYear, calInfo.currentJSMonthNumber + 1);
        const prevMonth = new Date(calInfo.currentDate);
        prevMonth.setMonth(calInfo.currentJSMonthNumber - 1);
        calInfo.prevMonthDays = daysInMonth(prevMonth.getFullYear(), prevMonth.getMonth() + 1);

        const nextMonth = new Date(calInfo.currentDate);
        nextMonth.setMonth(calInfo.currentJSMonthNumber + 1);

        const firstDate = new Date(calInfo.currentYear, calInfo.currentJSMonthNumber, 1);
        calInfo.currentMonthFirstDayOfWeek = firstDate.getDay();
        calInfo.currentMonthFirstDayOfWeekName = daysOfWeek[calInfo.currentMonthFirstDayOfWeek];

        const total = 42;
        var paddingDays = 0;
        var paddingDayNumbers = 0;
        if (calInfo.currentMonthFirstDayOfWeek !== 0) {
            paddingDays = calInfo.currentMonthFirstDayOfWeek;
            paddingDayNumbers = (calInfo.prevMonthDays - paddingDays + 1);
        }

        var paddingDayCount = paddingDays;
        var paddingDayNumber = paddingDayNumbers;
        console.log('calInfo', calInfo);
        setCalInfoState({...calInfo});

        let todayDt = `${new Date().getMonth() + 1}/${new Date().getDate()}/${new Date().getFullYear()}`;
        console.log("todayDt", todayDt);
        for (let index = 1; index <= total; index++) {
            let dayNumber = index;
            let isPaddingDay = false;
            let dt = `${prevMonth.getMonth() + 1}/${dayNumber}/${calInfo.currentYear}`;
            if (paddingDayCount > 0) {
                dayNumber = paddingDayNumber;
                isPaddingDay = true;
                dt = `${prevMonth.getMonth() + 1}/${paddingDayNumber}/${prevMonth.getFullYear()}`;
            } else {
                if (index > (paddingDays + calInfo.currentMonthDays)) {
                    dayNumber = index - (paddingDays + calInfo.currentMonthDays);
                    isPaddingDay = true;
                    dt = `${nextMonth.getMonth() + 1}/${dayNumber}/${nextMonth.getFullYear()}`;
                } else {
                    dayNumber = index - paddingDays;
                    isPaddingDay = false;
                    dt = `${calInfo.currentJSMonthNumber + 1}/${dayNumber}/${calInfo.currentYear}`;
                }
            }
            let day: Day = {
                uId: index,
                dayNumber: dayNumber,
                isPaddingDay: isPaddingDay,
                dt: dt,
                fullDt: new Date(dt).toUTCString(),
                showOrange: false,
                showYellow: false,
                showRed: false,
                isToday: todayDt === dt,
                calendarEvent: undefined
            }
            calInfo.dayList.push(day);
            paddingDayCount -= 1;
            paddingDayNumber += 1;
        }
        calInfo.dayList.forEach((dt) => {
            if (!dt.isPaddingDay) {
                dt.calendarEvent = orangeDays.find((d)=>d.eventDate === dt.dt) || yellowDays.find((d)=>d.eventDate === dt.dt) || redDays.find((d)=>d.eventDate === dt.dt);
                dt.showOrange = orangeDays.some((d)=>d.eventDate === dt.dt);
                dt.showYellow = yellowDays.some((d)=>d.eventDate === dt.dt);
                dt.showRed = redDays.some((d)=>d.eventDate === dt.dt);
            }
        })
        setCalInfoState({...calInfo}); 
    }

    const prevMonth = () => {
        const d = calInfoState.currentDate;
        d.setMonth(calInfoState.currentJSMonthNumber - 1);
        generateCalendar(d);
    }
    const nextMonth = () => {
        const d = calInfoState.currentDate;
        let newMonth = 0;
        if (calInfoState.currentJSMonthNumber === 11) {
            newMonth = 0;
            d.setFullYear(calInfoState.currentYear + 1);
        } else {
            newMonth = calInfoState.currentJSMonthNumber + 1;
        }
        d.setMonth(newMonth);
        generateCalendar(d);
    }

    const selectDay = (day: Day) => {
    if(day.calendarEvent){ 
        dispatch(selectCalendarEvent(day.calendarEvent!));
      } else {
        dispatch(selectCalendarEvent({} as CalendarEvent));
      }
    }

    useEffect(() => {
        generateCalendar(new Date());
    }, []);

    return (<div className="revnique-calendar">
        <div className="control-section">
            <div className="clickable fa-icon align-right" onClick={prevMonth}><FontAwesomeIcon icon={faChevronLeft} /></div>
            <div className="month-year-container"><span className="month-name">{calInfoState.currentMonthName}</span><span className="year-name">{calInfoState.currentYear}</span></div>
            <div className="clickable fa-icon" onClick={nextMonth}><FontAwesomeIcon icon={faChevronRight} /></div>
        </div>
        <div className="calendar-section">
            <div className="days-of-week-row">
                <div className="calendar-cell">Sun</div>
                <div className="calendar-cell">Mon</div>
                <div className="calendar-cell">Tue</div>
                <div className="calendar-cell">Wed</div>
                <div className="calendar-cell">Thu</div>
                <div className="calendar-cell">Fri</div>
                <div className="calendar-cell">Sat</div>
            </div>
            <div className="calendar-days">
                {calInfoState.dayList.map((day, index) => (
                    <div onClick={() => selectDay(day)} className={`calendar-cell ${day.isPaddingDay ? 'padding-day' : ''}`} key={index}
                        aria-label={day.fullDt} data-date={day.dt}>
                        <span className={`day-number ${day.showRed ? 'red-day' : ''} ${day.isToday ? 'today-day' : ''} ${day.showOrange ? 'orange-day' : ''} ${day.showYellow ? 'yellow-day' : ''}`}>{day.dayNumber}</span>
                    </div>
                ))}
            </div>
        </div>
        <div className="legend-section">
            <div className="legend-cell">
                <div className="legend-color today-day">&nbsp;</div>
                <div className="legend-label">Today</div>
            </div>
            <div className="legend-cell">
                <div className="legend-color red-day">&nbsp;</div>
                <div className="legend-label">Red</div>
            </div>
            <div className="legend-cell">
                <div className="legend-color orange-day">&nbsp;</div>
                <div className="legend-label">Orange</div>
            </div>
            <div className="legend-cell">
                <div className="legend-color yellow-day">&nbsp;</div>
                <div className="legend-label">Yellow</div>
            </div>
        </div>
    </div>);
}

export default RevniqueCalendar;

// apps/angular-portfolio/src/app/revnique-calendar/revnique-calendar.component.ts
import { Component, Input, OnChanges, OnInit, SimpleChanges } from '@angular/core';
import { Day } from './day.interface';
import { CommonModule } from '@angular/common';
import './date';
import { FontAwesomeModule } from '@fortawesome/angular-fontawesome';
import { faChevronLeft, faChevronRight } from '@fortawesome/free-solid-svg-icons';
import { CalendarEvent, PortfolioState } from '../../store/portfolio-store/portfolio.state';
import { PortfolioActions } from '../../store/portfolio-store/portfolio.actions';
import { Store } from '@ngrx/store';
@Component({
  selector: 'app-revnique-calendar',
  imports: [CommonModule, FontAwesomeModule],
  templateUrl: './revnique-calendar.component.html',
  styleUrl: './revnique-calendar.component.scss'
})
export class RevniqueCalendarComponent implements OnChanges {
  faChevronLeft = faChevronLeft;
  faChevronRight = faChevronRight;
  calInfo = {
    showTopRow: true,
    showBottomRow: true,
    currentDate: new Date(),
    currentJSMonthNumber: 0,
    currentMonthName: '',
    currentMonthDays: -1,
    currentYear: 0,
    prevMonthDays: 0,
    currentMonthFirstDayOfWeek: -1,
    currentMonthFirstDayOfWeekName: '',
    dayList: [] as Day[],
  }
  @Input() redDays: CalendarEvent[] = [];
  @Input() yellowDays: CalendarEvent[] = [];
  @Input() orangeDays: CalendarEvent[] = [];
  daysInMonth = (year:number, month:number) => new Date(year, month, 0).getDate();
  
  daysOfWeek = ['sunday', 'monday', 'tuesday', 'wednesday', 'thursday', 'friday', 'saturday' ];

  constructor(private store: Store<{ portfolio: PortfolioState }>) { }

  ngOnChanges(changes: SimpleChanges): void {
    this.generateCalendar(new Date());
  }
  
  generateCalendar(d: Date){ 
    this.calInfo.currentDate = d;
    console.log("generateCalendar", d);
    console.log("this.redDays", this.redDays);
    console.log("this.yellowDays", this.yellowDays);
    console.log("this.orangeDays", this.orangeDays);
    this.calInfo.currentJSMonthNumber = d.getMonth();
    this.calInfo.currentMonthName = d.getMonthName();

    this.calInfo.currentYear = d.getFullYear();
    this.calInfo.currentMonthDays = this.daysInMonth(this.calInfo.currentYear, this.calInfo.currentJSMonthNumber + 1);
    const prevMonth = new Date(this.calInfo.currentDate);
    prevMonth.setMonth(this.calInfo.currentJSMonthNumber - 1);
    this.calInfo.prevMonthDays = this.daysInMonth(prevMonth.getFullYear(), prevMonth.getMonth() + 1);

    const nextMonth = new Date(this.calInfo.currentDate);
    nextMonth.setMonth(this.calInfo.currentJSMonthNumber + 1);

    const firstDate = new Date(this.calInfo.currentYear,this.calInfo.currentJSMonthNumber,1);
    this.calInfo.currentMonthFirstDayOfWeek = firstDate.getDay();
    this.calInfo.currentMonthFirstDayOfWeekName = this.daysOfWeek[this.calInfo.currentMonthFirstDayOfWeek];

    const total = 42;
    var paddingDays = 0;
    var paddingDayNumbers = 0;
    if(this.calInfo.currentMonthFirstDayOfWeek !== 0){
      paddingDays = this.calInfo.currentMonthFirstDayOfWeek;
      paddingDayNumbers =  (this.calInfo.prevMonthDays - paddingDays + 1);
    }

    var paddingDayCount = paddingDays;
    var paddingDayNumber = paddingDayNumbers;
    this.calInfo.dayList = [];

    let todayDt = `${new Date().getMonth()+1}/${new Date().getDate()}/${new Date().getFullYear()}`;
    console.log("todayDt", todayDt);
    for (let index = 1; index <= total; index++) {
      let dayNumber = index;
      let isPaddingDay = false;
      let dt = `${prevMonth.getMonth()+1}/${dayNumber}/${this.calInfo.currentYear}`;
      if(paddingDayCount > 0){
        dayNumber = paddingDayNumber;
        isPaddingDay = true;
        dt = `${prevMonth.getMonth()+1}/${paddingDayNumber}/${prevMonth.getFullYear()}`;
      } else {
        if(index > (paddingDays + this.calInfo.currentMonthDays)){
          dayNumber = index - (paddingDays + this.calInfo.currentMonthDays);
          isPaddingDay = true;
          dt = `${nextMonth.getMonth()+1}/${dayNumber}/${nextMonth.getFullYear()}`;
        } else {
          dayNumber = index - paddingDays;
          isPaddingDay = false;
          dt = `${this.calInfo.currentJSMonthNumber+1}/${dayNumber}/${this.calInfo.currentYear}`;
        }
      }
      let day:Day = {
        uId: index,
        dayNumber:dayNumber,
        isPaddingDay: isPaddingDay,
        dt: dt,
        fullDt: new Date(dt).toUTCString(),
        showOrange: false,
        showYellow: false,
        showRed: false,
        isToday: todayDt === dt,
        calendarEvent: undefined
      }
      this.calInfo.dayList.push(day);
      paddingDayCount -= 1;
      paddingDayNumber +=1;
    }
    this.calInfo.dayList.forEach((dt)=>{
      if(!dt.isPaddingDay){
        dt.calendarEvent = this.orangeDays.find((d)=>d.eventDate === dt.dt) || this.yellowDays.find((d)=>d.eventDate === dt.dt) || this.redDays.find((d)=>d.eventDate === dt.dt);
        dt.showOrange = this.orangeDays.some((d)=>d.eventDate === dt.dt);
        dt.showYellow = this.yellowDays.some((d)=>d.eventDate === dt.dt);
        dt.showRed = this.redDays.some((d)=>d.eventDate === dt.dt);
      }
    })
  }

  selectDay(day: Day){
    if(day.calendarEvent){  
      this.store.dispatch(PortfolioActions.selectCalendarEvent({
        event: day.calendarEvent!
      }));
    } else {
      this.store.dispatch(PortfolioActions.selectCalendarEvent({
        event: null
      }));
    }
  }

  prevMonth() {
    const d = this.calInfo.currentDate;
    d.setMonth(this.calInfo.currentJSMonthNumber - 1);
    this.generateCalendar(d);
  }
  nextMonth() {
    const d = this.calInfo.currentDate;
    let newMonth = 0;
    if (this.calInfo.currentJSMonthNumber === 11) {
      newMonth = 0;
      d.setFullYear(this.calInfo.currentYear + 1);
    } else {
      newMonth = this.calInfo.currentJSMonthNumber + 1;
    }
    d.setMonth(newMonth);
    this.generateCalendar(d);
  }
}











// import { Component, Input, OnDestroy, OnInit } from '@angular/core';
// import { AuthState, initialAuthState } from '../../../../core/state/root/root.state';
// import { Store } from '@ngrx/store';
// import { AssociateDashboardActions } from '../../state/associate-dashboard.actions';
// import { selectAssociateDashboardState, selectDaysDataState } from '../../state/associate-dashboard.selector';
// import { Subject, takeUntil } from 'rxjs';
// import { formatDate } from '@angular/common';
// import { CalendarDay } from '../../models/user-projection.model';

// @Component({
//   selector: 'app-time-management',
//   templateUrl: './time-management.component.html',
//   styleUrl: './time-management.component.scss'
// })
// export class TimeManagementComponent implements OnInit, OnDestroy{
//   @Input() authState: AuthState = initialAuthState;
//   daysDataState$ = this.store.select(selectDaysDataState); //just the specific slice because higher up it will load anytime anything in that slice changes
//   associateDashboardState$ = this.store.select(selectAssociateDashboardState);
//   destroy$: Subject<boolean> = new Subject<boolean>();
//   calInfo = {
//     showTopRow: true,
//     showBottomRow: true,
//     currentDate: new Date(),
//     currentJSMonthNumber: 0,
//     currentMonthName: '',
//     currentMonthDays: -1,
//     currentYear: 0,
//     prevMonthDays: 0,
//     currentMonthFirstDayOfWeek: -1,
//     currentMonthFirstDayOfWeekName: '',
//     dayList: [{isPaddingDay:false, dt:'', showOrange: false, showRed:false, showBlue:false, dayNumber:0, fullDt:new Date().toUTCString()}],
//   }
  
//   // redDays = ['6/3/2025','6/8/2025','6/28/2025','6/29/2025','5/17/2025','5/28/2025','7/27/2025','7/11/2025'];
//   // blueDays = ['6/2/2025','6/8/2025','6/18/2025','6/21/2025','5/7/2025','5/2/2025','7/7/2025','7/21/2025'];
  
//   redDays = [''];
//   blueDays = [''];
//   orangeDays = [''];
//   daysInMonth = (year:number, month:number) => new Date(year, month, 0).getDate();
//   daysOfWeek = ['sunday', 'monday', 'tuesday', 'wednesday', 'thursday', 'friday', 'saturday' ];

//   constructor(private store: Store){}
//   ngOnInit(): void {
//     this.loadCalendar(new Date());
//     this.daysDataState$.pipe(takeUntil(this.destroy$)).subscribe((daysData)=>{
//       if(daysData && daysData.length !== undefined){
//         this.orangeDays = daysData.map((d:any)=> formatDate(new Date(d.dateOfEntry),'M/d/yyyy', 'en-US'));
//         this.generateCalendar(this.calInfo.currentDate);
//       }
//     });
//   }

//   loadCalendar(d:Date){
//     this.calInfo.currentDate = d;
//     const currentYear = d.getFullYear();
//     const currentJSMonthNumber = d.getMonth();
//     const currentMonthDays = this.daysInMonth(currentYear, currentJSMonthNumber + 1);
//     const firstDate = new Date(currentYear,currentJSMonthNumber,1);
//     const endDate = new Date(`${firstDate.getMonth()+1}/${currentMonthDays}/${currentYear}`);
//     this.store.dispatch(AssociateDashboardActions.loadCalendarData({userID:this.authState.currentUser!.userID, startDate:firstDate, endDate}));
//   }

//   generateCalendar(d: Date){ 
//     this.calInfo.currentJSMonthNumber = d.getMonth();
//     this.calInfo.currentMonthName = this.getMonthName(d);

//     this.calInfo.currentYear = d.getFullYear();
//     this.calInfo.currentMonthDays = this.daysInMonth(this.calInfo.currentYear, this.calInfo.currentJSMonthNumber + 1);
//     const prevMonth = new Date(this.calInfo.currentDate);
//     prevMonth.setMonth(this.calInfo.currentJSMonthNumber - 1);
//     this.calInfo.prevMonthDays = this.daysInMonth(prevMonth.getFullYear(), prevMonth.getMonth() + 1);

//     const nextMonth = new Date(this.calInfo.currentDate);
//     nextMonth.setMonth(this.calInfo.currentJSMonthNumber + 1);

//     const firstDate = new Date(this.calInfo.currentYear,this.calInfo.currentJSMonthNumber,1);
//     this.calInfo.currentMonthFirstDayOfWeek = firstDate.getDay();
//     this.calInfo.currentMonthFirstDayOfWeekName = this.daysOfWeek[this.calInfo.currentMonthFirstDayOfWeek];

//     const total = 42;
//     var paddingDays = 0;
//     var paddingDayNumbers = 0;
//     if(this.calInfo.currentMonthFirstDayOfWeek !== 0){
//       paddingDays = this.calInfo.currentMonthFirstDayOfWeek;
//       paddingDayNumbers =  (this.calInfo.prevMonthDays - paddingDays + 1);
//     }

//     var paddingDayCount = paddingDays;
//     var paddingDayNumber = paddingDayNumbers;
//     this.calInfo.dayList = [];
//     for (let index = 1; index <= total; index++) {
//       let dayNumber = index;
//       let isPaddingDay = false;
//       let dt = `${prevMonth.getMonth()+1}/${dayNumber}/${this.calInfo.currentYear}`;
//       if(paddingDayCount > 0){
//         dayNumber = paddingDayNumber;
//         isPaddingDay = true;
//         dt = `${prevMonth.getMonth()+1}/${paddingDayNumber}/${prevMonth.getFullYear()}`;
//       } else {
//         if(index > (paddingDays + this.calInfo.currentMonthDays)){
//           dayNumber = index - (paddingDays + this.calInfo.currentMonthDays);
//           isPaddingDay = true;
//           dt = `${nextMonth.getMonth()+1}/${dayNumber}/${nextMonth.getFullYear()}`;
//         } else {
//           dayNumber = index - paddingDays;
//           isPaddingDay = false;
//           dt = `${this.calInfo.currentJSMonthNumber+1}/${dayNumber}/${this.calInfo.currentYear}`;
//         }
//       }
//       let day:CalendarDay = {
//         uId: index,
//         dayNumber:dayNumber,
//         isPaddingDay: isPaddingDay,
//         dt: dt,
//         fullDt: new Date(dt).toUTCString(),
//         showOrange: false,
//         showBlue: false,
//         showRed: false
//       }
//       this.calInfo.dayList.push(day);
//       paddingDayCount -= 1;
//       paddingDayNumber +=1;
//     }
//     this.calInfo.dayList.forEach((dt)=>{
//       if(!dt.isPaddingDay){
//         dt.showOrange = this.orangeDays.some((d)=>d === dt.dt);
//         dt.showBlue = this.blueDays.some((d)=>d === dt.dt);
//         dt.showRed = this.redDays.some((d)=>d === dt.dt);
//       }
//     })
//   }

//   prevMonth() {
//     const d = this.calInfo.currentDate;
//     d.setMonth(this.calInfo.currentJSMonthNumber - 1);
//     this.loadCalendar(d);
//   }

//   nextMonth() {
//     const d = this.calInfo.currentDate;
//     let newMonth = 0;
//     if (this.calInfo.currentJSMonthNumber === 11) {
//       newMonth = 0;
//       d.setFullYear(this.calInfo.currentYear + 1);
//     } else {
//       newMonth = this.calInfo.currentJSMonthNumber + 1;
//     }
//     d.setMonth(newMonth);
//     this.loadCalendar(d);
//   }

//   getMonthName = function (dt: Date) {
//     var m = dt.getMonth();
//     var rtn = "";
//     switch (m) {
//       case 0:
//         rtn = "January";
//         break;
//       case 1:
//         rtn = "February";
//         break;
//       case 2:
//         rtn = "March";
//         break;
//       case 3:
//         rtn = "April";
//         break;
//       case 4:
//         rtn = "May";
//         break;
//       case 5:
//         rtn = "June";
//         break;
//       case 6:
//         rtn = "July";
//         break;
//       case 7:
//         rtn = "August";
//         break;
//       case 8:
//         rtn = "September";
//         break;
//       case 9:
//         rtn = "October";
//         break;
//       case 10:
//         rtn = "November";
//         break;
//       case 11:
//         rtn = "December";
//         break;
//     }
//     return rtn;
//   };

//   ngOnDestroy(): void {
//     this.destroy$.next(true);
//     this.destroy$.unsubscribe();
//   }
// }
<div class="revnique-calendar">
    <div class="control-section">
        <div (click)="prevMonth()" class="clickable fa-icon align-right"><fa-icon [icon]="faChevronLeft"></fa-icon></div>
        <div class="month-year-container"><span class="month-name">{{calInfo.currentMonthName}}</span><span class="year-name">{{calInfo.currentYear}}</span></div>
        <div (click)="nextMonth()" class="clickable fa-icon"><fa-icon [icon]="faChevronRight"></fa-icon></div>
    </div>
    <div class="calendar-section">
        <div class="days-of-week-row">
            <div class="calendar-cell">Sun</div>
            <div class="calendar-cell">Mon</div>
            <div class="calendar-cell">Tue</div>
            <div class="calendar-cell">Wed</div>
            <div class="calendar-cell">Thu</div>
            <div class="calendar-cell">Fri</div>
            <div class="calendar-cell">Sat</div>
        </div>
        <div class="calendar-days">
            <ng-container *ngFor="let day of calInfo.dayList; let _i = index">
                <div class="calendar-cell" [ngClass]="{'padding-day':day.isPaddingDay}" (click)="selectDay(day)"
                    attr.aria-label="{{day.fullDt}}" attr.aria-date="{{day.dt}}">
                    <span class="day-number" [ngClass]="{'red-day':day.showRed, 'today-day':day.isToday, 'orange-day':day.showOrange, 'yellow-day':day.showYellow}">{{day.dayNumber}}</span>
                </div>
            </ng-container>
        </div>
    </div>
    <div class="legend-section">
        <div class="legend-cell">
            <div class="legend-color today-day">&nbsp;</div>
            <div class="legend-label">Today</div>
        </div>
        <div class="legend-cell">
            <div class="legend-color red-day">&nbsp;</div>
            <div class="legend-label">Red</div>
        </div>
        <div class="legend-cell">
            <div class="legend-color orange-day">&nbsp;</div>
            <div class="legend-label">Orange</div>
        </div>
        <div class="legend-cell">
            <div class="legend-color yellow-day">&nbsp;</div>
            <div class="legend-label">Yellow</div>
        </div>
    </div>
</div>
